### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by coderdiaz** [vues-team/website#21]
Add responsive support to the site since the desktop version has been prioritized for the time being.

The responsible for this issue should adapt the site to the most important types of screen, at the moment to have a minimum viable version.

**Comment by nandomoreirame** [comment]
@coderdiaz  I can also do this, along with the issue #32

**Comment by coderdiaz** [comment]
Nice, thanks 👍

**Comment by DigitalDesignerOnline** [comment]
I figured this was part of fixing the website ;) on it

**Comment by coderdiaz** [comment]
@DigitalDesignerOnline Yes, @nandomoreirame it works in this issue

**Comment by coderdiaz** [comment]
Fixed #41
