### ISSUE TITLE
Website structure to bootstrap 4

### ISSUE THREAD

**Issue by coderdiaz** [vues-team/website#32]
You already have Bootstrap 4 styles loaded in the project, now that the structure is modified so that it is coupled with bootstrap styles, if in this same task you can close the corresponding job responsive you can do.

Reference with #21

**Comment by Jataki** [comment]
Hi, can you please translate the task to english? I'm not understanding your request. Are you asking to use Bootstrap to modify your pages?

**Comment by coderdiaz** [comment]
@Jataki Just change the html structure of the site to bootstrap 4 so that it adapts to the new features of the framework

**Comment by nandomoreirame** [comment]
@coderdiaz I can do this if you want 😃

**Comment by coderdiaz** [comment]
@nandomoreirame nice :)

**Comment by nandomoreirame** [comment]
This pull request will have 2 parts:
- Installing and configuring the Bootstrap: #33
- Change tags and classes in HTML for bootstrap use: in progress

**Comment by nandomoreirame** [comment]
Hey @coderdiaz , this project uses the framework [Primer](http://primercss.io/) by Github, will it be removed?

**Comment by coderdiaz** [comment]
@nandomoreirame yes, please
