### ISSUE TITLE
Fixing website design

### ISSUE THREAD

**Issue by coderdiaz** [vues-team/website#35]
- Add a better UI design to website

**Comment by DigitalDesignerOnline** [comment]
Hi I would be happy to assist, I will fork your repo and get started right away.

**Comment by DigitalDesignerOnline** [comment]
I can see we need to address mobile styling, are there any specifics you would like to see different?

**Comment by coderdiaz** [comment]
@DigitalDesignerOnline Hi, at the moment, we only have a basic styles for show posts in site, but we need a better design with colors, typography and visual enhancements

**Comment by DigitalDesignerOnline** [comment]
sounds good mate, will see what I can do, its long weekend so I have some time to kill out here in Canada for our Thanksgiving :)

**Comment by coderdiaz** [comment]
@DigitalDesignerOnline Nice, thanks :3

**Comment by coderdiaz** [comment]
Fixed #41
